### ISSUE TITLE
Document how to preview blog locally using Jekyll

### ISSUE THREAD

**Issue by apetro** [apereo/apereo.github.io#23]
Part of the premise of GitHub Pages and end to end open tool chains is that while GitHub Pages provides a delightful confident SaaS implementation that in practice we'll just use, in principle we could pick up and move the whole site to independent hosting overnight.

The content is open (Markdown files, JS, CSS, HTML templates). The tool chain is open (Jekyll, complete with GitHub pages special sauce gems). So just a matter of running it elsewhere.

Except. When I try to run the tool chain on my laptop, I don't successfully generate the site. cf #13 .

Getting this working is important because it enables local development not just of content but of everything else too, like tagging support, templates, everything.

**Comment by mindblender** [comment]
I can take a stab and documenting the process I use locally, since I have got it working to test my UI changes.

**Comment by apetro** [comment]
This isn't a patch, it's an outstanding issue. As viable next steps: could @mindblender share additional hints about how he's gotten this working? I'd appreciate that. Alternatively, anyone else have this site rendering locally?

**Comment by mindblender** [comment]
@apetro Just submitted a PR that appears to work on my end.  Would you mind reviewing and testing it on your local box?  thanks!
