### ISSUE TITLE
Request Name Change

### ISSUE THREAD

**Issue by iandolphin** [apereo/apereo.github.io#39]
This blog is named to suggest that it is an official voice of the Apereo Foundation. After consulting the Foundation Board Chair, I would like to request that it be changed to reflect the fact that it is not. For legal reasons, official statements on behalf of the Foundation are made by the Chair, ED, or other other authorized individual.

**Comment by mmoayyed** [comment]
@iandolphin Does this verbiage help?
https://apereo.github.io/about/

**Comment by iandolphin** [comment]
It does - and thanks for the quick response. Apereo Community Blog or similar would work also - I'd prefer to see the word "Foundation" removed if possible - then it's crystal clear without needing to read the small print.

**Comment by mmoayyed** [comment]
Of course. Done.

**Comment by iandolphin** [comment]
Thanks - perfect!

**Comment by apetro** [comment]
Adjusted repository description to match.

![adjusted-repo-description-arrrow](https://user-images.githubusercontent.com/952283/31497981-5dd672b8-af26-11e7-8929-5e4054d27ec0.png)
