### ISSUE TITLE
Question regarding blog post (possible room for clarification)

### ISSUE THREAD

**Issue by arbner** [apereo/apereo.github.io#44]
In [this blog post](https://github.com/apereo/apereo.github.io/blob/master/_posts/cas/2018-01-05-cas-deployment-with-proxy.md) about CAS behind a proxy setup, I stumbled upon the following sentence:

```F5, HAProxy, etc. In most setups, the proxy upfront terminates SSL and then hands off the request over to CAS on a secured connection typically on port 8080.```

Could you clarify what you understand by a secured connection in this case? How to secure the connection when SSL is terminated at the load balancer?

**Comment by apetro** [comment]
It's not a patch, it's a question. It'd be a fine thing to update the post to answer the question.
